//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.30 at 03:52:31 PM MSK 
//


package ru.grinn.diadocsoap.xjs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcceptanceCertificateSignatureInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcceptanceCertificateSignatureInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Official" type="{}Official" minOccurs="0"/&gt;
 *         &lt;element name="Attorney" type="{}Attorney" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SignatureDate" type="{}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcceptanceCertificateSignatureInfo", propOrder = {
    "official",
    "attorney"
})
public class AcceptanceCertificateSignatureInfo {

    @XmlElement(name = "Official")
    protected Official official;
    @XmlElement(name = "Attorney")
    protected Attorney attorney;
    @XmlAttribute(name = "SignatureDate")
    protected String signatureDate;

    /**
     * Gets the value of the official property.
     * 
     * @return
     *     possible object is
     *     {@link Official }
     *     
     */
    public Official getOfficial() {
        return official;
    }

    /**
     * Sets the value of the official property.
     * 
     * @param value
     *     allowed object is
     *     {@link Official }
     *     
     */
    public void setOfficial(Official value) {
        this.official = value;
    }

    /**
     * Gets the value of the attorney property.
     * 
     * @return
     *     possible object is
     *     {@link Attorney }
     *     
     */
    public Attorney getAttorney() {
        return attorney;
    }

    /**
     * Sets the value of the attorney property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attorney }
     *     
     */
    public void setAttorney(Attorney value) {
        this.attorney = value;
    }

    /**
     * Gets the value of the signatureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureDate() {
        return signatureDate;
    }

    /**
     * Sets the value of the signatureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureDate(String value) {
        this.signatureDate = value;
    }

}
