//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.30 at 04:23:44 PM MSK 
//


package ru.grinn.diadocsoap.xjs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CorrectableInvoiceItemFields_WithTwentyPercent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CorrectableInvoiceItemFields_WithTwentyPercent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}CorrectableInvoiceItemFields_WithoutTaxRate"&gt;
 *       &lt;attribute name="TaxRate" use="required" type="{}TaxRateWithTwentyPercent" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorrectableInvoiceItemFields_WithTwentyPercent")
public class CorrectableInvoiceItemFieldsWithTwentyPercent
    extends CorrectableInvoiceItemFieldsWithoutTaxRate
{

    @XmlAttribute(name = "TaxRate", required = true)
    protected String taxRate;

    /**
     * Gets the value of the taxRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxRate() {
        return taxRate;
    }

    /**
     * Sets the value of the taxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxRate(String value) {
        this.taxRate = value;
    }

}
