//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.12 at 05:04:03 PM MSK 
//


package ru.grinn.diadocsoap.xjs;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ТаблСчФакт - Сведения таблицы счет фактуры
 * 
 * <p>Java class for InvoiceTable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceTable"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Item" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element name="CustomsDeclarations" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="CustomsDeclaration" type="{}CustomsDeclarationWithHyphens" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="AdditionalInfos" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="AdditionalInfo" type="{}AdditionalInfo" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ItemTracingInfos" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ItemTracingInfo" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="RegNumberUnit" use="required" type="{}string29" /&gt;
 *                                     &lt;attribute name="Unit" use="required" type="{}okei" /&gt;
 *                                     &lt;attribute name="Quantity" use="required"&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                                           &lt;totalDigits value="26"/&gt;
 *                                           &lt;fractionDigits value="11"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/attribute&gt;
 *                                     &lt;attribute name="ItemAddInfo" type="{}string255" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ItemIdentificationNumbers" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ItemIdentificationNumber" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;choice&gt;
 *                                       &lt;element name="Unit" type="{}string255" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                                       &lt;element name="PackageId" type="{}string255" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                                     &lt;/choice&gt;
 *                                     &lt;attribute name="TransPackageId" type="{}string255" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/all&gt;
 *                 &lt;attribute name="Product" type="{}string1000" /&gt;
 *                 &lt;attribute name="Unit" type="{}okei" /&gt;
 *                 &lt;attribute name="HyphenUnit" default="false"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;enumeration value="true"/&gt;
 *                       &lt;enumeration value="false"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="UnitName" type="{}string255" /&gt;
 *                 &lt;attribute name="Quantity"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                       &lt;totalDigits value="26"/&gt;
 *                       &lt;fractionDigits value="11"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="Price"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                       &lt;totalDigits value="26"/&gt;
 *                       &lt;fractionDigits value="11"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="Excise"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                       &lt;totalDigits value="19"/&gt;
 *                       &lt;fractionDigits value="2"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="TaxRate" use="required" type="{}TaxRateWithTwentyPercentAndTaxedByAgent" /&gt;
 *                 &lt;attribute name="SubtotalWithVatExcluded"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                       &lt;totalDigits value="19"/&gt;
 *                       &lt;fractionDigits value="2"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="Vat"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                       &lt;totalDigits value="19"/&gt;
 *                       &lt;fractionDigits value="2"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="WithoutVat" default="false"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;enumeration value="true"/&gt;
 *                       &lt;enumeration value="false"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="HyphenVat" default="false"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;enumeration value="true"/&gt;
 *                       &lt;enumeration value="false"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="Subtotal"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                       &lt;totalDigits value="19"/&gt;
 *                       &lt;fractionDigits value="2"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="HyphenSubtotal" default="false"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;enumeration value="true"/&gt;
 *                       &lt;enumeration value="false"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="ItemMark"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                       &lt;enumeration value="1"/&gt;
 *                       &lt;enumeration value="2"/&gt;
 *                       &lt;enumeration value="3"/&gt;
 *                       &lt;enumeration value="4"/&gt;
 *                       &lt;enumeration value="5"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="AdditionalProperty"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;minLength value="1"/&gt;
 *                       &lt;maxLength value="4"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="ItemVendorCode" type="{}string255" /&gt;
 *                 &lt;attribute name="ItemToRelease"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                       &lt;totalDigits value="26"/&gt;
 *                       &lt;fractionDigits value="11"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="ItemCharact" type="{}string1000" /&gt;
 *                 &lt;attribute name="ItemArticle" type="{}string50" /&gt;
 *                 &lt;attribute name="ItemKind" type="{}string10" /&gt;
 *                 &lt;attribute name="CatalogCode"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;length value="27"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="ItemTypeCode" type="{}string10" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="TotalWithVatExcluded"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;totalDigits value="19"/&gt;
 *             &lt;fractionDigits value="2"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Vat"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;totalDigits value="19"/&gt;
 *             &lt;fractionDigits value="2"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="WithoutVat" default="false"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="HyphenVat" default="false"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Total"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;totalDigits value="19"/&gt;
 *             &lt;fractionDigits value="2"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="HyphenTotal" default="false"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="TotalNet"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;totalDigits value="26"/&gt;
 *             &lt;fractionDigits value="11"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceTable", propOrder = {
    "item"
})
public class InvoiceTable {

    @XmlElement(name = "Item", required = true)
    protected List<InvoiceTable.Item> item;
    @XmlAttribute(name = "TotalWithVatExcluded")
    protected BigDecimal totalWithVatExcluded;
    @XmlAttribute(name = "Vat")
    protected BigDecimal vat;
    @XmlAttribute(name = "WithoutVat")
    protected String withoutVat;
    @XmlAttribute(name = "HyphenVat")
    protected String hyphenVat;
    @XmlAttribute(name = "Total")
    protected BigDecimal total;
    @XmlAttribute(name = "HyphenTotal")
    protected String hyphenTotal;
    @XmlAttribute(name = "TotalNet")
    protected BigDecimal totalNet;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceTable.Item }
     * 
     * 
     */
    public List<InvoiceTable.Item> getItem() {
        if (item == null) {
            item = new ArrayList<InvoiceTable.Item>();
        }
        return this.item;
    }

    /**
     * Gets the value of the totalWithVatExcluded property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalWithVatExcluded() {
        return totalWithVatExcluded;
    }

    /**
     * Sets the value of the totalWithVatExcluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalWithVatExcluded(BigDecimal value) {
        this.totalWithVatExcluded = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVat() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVat(BigDecimal value) {
        this.vat = value;
    }

    /**
     * Gets the value of the withoutVat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWithoutVat() {
        if (withoutVat == null) {
            return "false";
        } else {
            return withoutVat;
        }
    }

    /**
     * Sets the value of the withoutVat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWithoutVat(String value) {
        this.withoutVat = value;
    }

    /**
     * Gets the value of the hyphenVat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHyphenVat() {
        if (hyphenVat == null) {
            return "false";
        } else {
            return hyphenVat;
        }
    }

    /**
     * Sets the value of the hyphenVat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHyphenVat(String value) {
        this.hyphenVat = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotal(BigDecimal value) {
        this.total = value;
    }

    /**
     * Gets the value of the hyphenTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHyphenTotal() {
        if (hyphenTotal == null) {
            return "false";
        } else {
            return hyphenTotal;
        }
    }

    /**
     * Sets the value of the hyphenTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHyphenTotal(String value) {
        this.hyphenTotal = value;
    }

    /**
     * Gets the value of the totalNet property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalNet() {
        return totalNet;
    }

    /**
     * Sets the value of the totalNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalNet(BigDecimal value) {
        this.totalNet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element name="CustomsDeclarations" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="CustomsDeclaration" type="{}CustomsDeclarationWithHyphens" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="AdditionalInfos" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="AdditionalInfo" type="{}AdditionalInfo" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ItemTracingInfos" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ItemTracingInfo" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="RegNumberUnit" use="required" type="{}string29" /&gt;
     *                           &lt;attribute name="Unit" use="required" type="{}okei" /&gt;
     *                           &lt;attribute name="Quantity" use="required"&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *                                 &lt;totalDigits value="26"/&gt;
     *                                 &lt;fractionDigits value="11"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/attribute&gt;
     *                           &lt;attribute name="ItemAddInfo" type="{}string255" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ItemIdentificationNumbers" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ItemIdentificationNumber" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;choice&gt;
     *                             &lt;element name="Unit" type="{}string255" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                             &lt;element name="PackageId" type="{}string255" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                           &lt;/choice&gt;
     *                           &lt;attribute name="TransPackageId" type="{}string255" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/all&gt;
     *       &lt;attribute name="Product" type="{}string1000" /&gt;
     *       &lt;attribute name="Unit" type="{}okei" /&gt;
     *       &lt;attribute name="HyphenUnit" default="false"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="true"/&gt;
     *             &lt;enumeration value="false"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="UnitName" type="{}string255" /&gt;
     *       &lt;attribute name="Quantity"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *             &lt;totalDigits value="26"/&gt;
     *             &lt;fractionDigits value="11"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="Price"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *             &lt;totalDigits value="26"/&gt;
     *             &lt;fractionDigits value="11"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="Excise"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *             &lt;totalDigits value="19"/&gt;
     *             &lt;fractionDigits value="2"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="TaxRate" use="required" type="{}TaxRateWithTwentyPercentAndTaxedByAgent" /&gt;
     *       &lt;attribute name="SubtotalWithVatExcluded"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *             &lt;totalDigits value="19"/&gt;
     *             &lt;fractionDigits value="2"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="Vat"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *             &lt;totalDigits value="19"/&gt;
     *             &lt;fractionDigits value="2"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="WithoutVat" default="false"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="true"/&gt;
     *             &lt;enumeration value="false"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="HyphenVat" default="false"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="true"/&gt;
     *             &lt;enumeration value="false"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="Subtotal"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *             &lt;totalDigits value="19"/&gt;
     *             &lt;fractionDigits value="2"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="HyphenSubtotal" default="false"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="true"/&gt;
     *             &lt;enumeration value="false"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="ItemMark"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
     *             &lt;enumeration value="1"/&gt;
     *             &lt;enumeration value="2"/&gt;
     *             &lt;enumeration value="3"/&gt;
     *             &lt;enumeration value="4"/&gt;
     *             &lt;enumeration value="5"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="AdditionalProperty"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;minLength value="1"/&gt;
     *             &lt;maxLength value="4"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="ItemVendorCode" type="{}string255" /&gt;
     *       &lt;attribute name="ItemToRelease"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *             &lt;totalDigits value="26"/&gt;
     *             &lt;fractionDigits value="11"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="ItemCharact" type="{}string1000" /&gt;
     *       &lt;attribute name="ItemArticle" type="{}string50" /&gt;
     *       &lt;attribute name="ItemKind" type="{}string10" /&gt;
     *       &lt;attribute name="CatalogCode"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;length value="27"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="ItemTypeCode" type="{}string10" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Item {

        @XmlElement(name = "CustomsDeclarations")
        protected InvoiceTable.Item.CustomsDeclarations customsDeclarations;
        @XmlElement(name = "AdditionalInfos")
        protected InvoiceTable.Item.AdditionalInfos additionalInfos;
        @XmlElement(name = "ItemTracingInfos")
        protected InvoiceTable.Item.ItemTracingInfos itemTracingInfos;
        @XmlElement(name = "ItemIdentificationNumbers")
        protected InvoiceTable.Item.ItemIdentificationNumbers itemIdentificationNumbers;
        @XmlAttribute(name = "Product")
        protected String product;
        @XmlAttribute(name = "Unit")
        protected String unit;
        @XmlAttribute(name = "HyphenUnit")
        protected String hyphenUnit;
        @XmlAttribute(name = "UnitName")
        protected String unitName;
        @XmlAttribute(name = "Quantity")
        protected BigDecimal quantity;
        @XmlAttribute(name = "Price")
        protected BigDecimal price;
        @XmlAttribute(name = "Excise")
        protected BigDecimal excise;
        @XmlAttribute(name = "TaxRate", required = true)
        protected String taxRate;
        @XmlAttribute(name = "SubtotalWithVatExcluded")
        protected BigDecimal subtotalWithVatExcluded;
        @XmlAttribute(name = "Vat")
        protected BigDecimal vat;
        @XmlAttribute(name = "WithoutVat")
        protected String withoutVat;
        @XmlAttribute(name = "HyphenVat")
        protected String hyphenVat;
        @XmlAttribute(name = "Subtotal")
        protected BigDecimal subtotal;
        @XmlAttribute(name = "HyphenSubtotal")
        protected String hyphenSubtotal;
        @XmlAttribute(name = "ItemMark")
        protected BigInteger itemMark;
        @XmlAttribute(name = "AdditionalProperty")
        protected String additionalProperty;
        @XmlAttribute(name = "ItemVendorCode")
        protected String itemVendorCode;
        @XmlAttribute(name = "ItemToRelease")
        protected BigDecimal itemToRelease;
        @XmlAttribute(name = "ItemCharact")
        protected String itemCharact;
        @XmlAttribute(name = "ItemArticle")
        protected String itemArticle;
        @XmlAttribute(name = "ItemKind")
        protected String itemKind;
        @XmlAttribute(name = "CatalogCode")
        protected String catalogCode;
        @XmlAttribute(name = "ItemTypeCode")
        protected String itemTypeCode;

        /**
         * Gets the value of the customsDeclarations property.
         * 
         * @return
         *     possible object is
         *     {@link InvoiceTable.Item.CustomsDeclarations }
         *     
         */
        public InvoiceTable.Item.CustomsDeclarations getCustomsDeclarations() {
            return customsDeclarations;
        }

        /**
         * Sets the value of the customsDeclarations property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvoiceTable.Item.CustomsDeclarations }
         *     
         */
        public void setCustomsDeclarations(InvoiceTable.Item.CustomsDeclarations value) {
            this.customsDeclarations = value;
        }

        /**
         * Gets the value of the additionalInfos property.
         * 
         * @return
         *     possible object is
         *     {@link InvoiceTable.Item.AdditionalInfos }
         *     
         */
        public InvoiceTable.Item.AdditionalInfos getAdditionalInfos() {
            return additionalInfos;
        }

        /**
         * Sets the value of the additionalInfos property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvoiceTable.Item.AdditionalInfos }
         *     
         */
        public void setAdditionalInfos(InvoiceTable.Item.AdditionalInfos value) {
            this.additionalInfos = value;
        }

        /**
         * Gets the value of the itemTracingInfos property.
         * 
         * @return
         *     possible object is
         *     {@link InvoiceTable.Item.ItemTracingInfos }
         *     
         */
        public InvoiceTable.Item.ItemTracingInfos getItemTracingInfos() {
            return itemTracingInfos;
        }

        /**
         * Sets the value of the itemTracingInfos property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvoiceTable.Item.ItemTracingInfos }
         *     
         */
        public void setItemTracingInfos(InvoiceTable.Item.ItemTracingInfos value) {
            this.itemTracingInfos = value;
        }

        /**
         * Gets the value of the itemIdentificationNumbers property.
         * 
         * @return
         *     possible object is
         *     {@link InvoiceTable.Item.ItemIdentificationNumbers }
         *     
         */
        public InvoiceTable.Item.ItemIdentificationNumbers getItemIdentificationNumbers() {
            return itemIdentificationNumbers;
        }

        /**
         * Sets the value of the itemIdentificationNumbers property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvoiceTable.Item.ItemIdentificationNumbers }
         *     
         */
        public void setItemIdentificationNumbers(InvoiceTable.Item.ItemIdentificationNumbers value) {
            this.itemIdentificationNumbers = value;
        }

        /**
         * Gets the value of the product property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProduct() {
            return product;
        }

        /**
         * Sets the value of the product property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProduct(String value) {
            this.product = value;
        }

        /**
         * Gets the value of the unit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnit() {
            return unit;
        }

        /**
         * Sets the value of the unit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnit(String value) {
            this.unit = value;
        }

        /**
         * Gets the value of the hyphenUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHyphenUnit() {
            if (hyphenUnit == null) {
                return "false";
            } else {
                return hyphenUnit;
            }
        }

        /**
         * Sets the value of the hyphenUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHyphenUnit(String value) {
            this.hyphenUnit = value;
        }

        /**
         * Gets the value of the unitName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitName() {
            return unitName;
        }

        /**
         * Sets the value of the unitName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitName(String value) {
            this.unitName = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setQuantity(BigDecimal value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPrice(BigDecimal value) {
            this.price = value;
        }

        /**
         * Gets the value of the excise property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getExcise() {
            return excise;
        }

        /**
         * Sets the value of the excise property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setExcise(BigDecimal value) {
            this.excise = value;
        }

        /**
         * Gets the value of the taxRate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxRate() {
            return taxRate;
        }

        /**
         * Sets the value of the taxRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxRate(String value) {
            this.taxRate = value;
        }

        /**
         * Gets the value of the subtotalWithVatExcluded property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSubtotalWithVatExcluded() {
            return subtotalWithVatExcluded;
        }

        /**
         * Sets the value of the subtotalWithVatExcluded property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSubtotalWithVatExcluded(BigDecimal value) {
            this.subtotalWithVatExcluded = value;
        }

        /**
         * Gets the value of the vat property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getVat() {
            return vat;
        }

        /**
         * Sets the value of the vat property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setVat(BigDecimal value) {
            this.vat = value;
        }

        /**
         * Gets the value of the withoutVat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWithoutVat() {
            if (withoutVat == null) {
                return "false";
            } else {
                return withoutVat;
            }
        }

        /**
         * Sets the value of the withoutVat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWithoutVat(String value) {
            this.withoutVat = value;
        }

        /**
         * Gets the value of the hyphenVat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHyphenVat() {
            if (hyphenVat == null) {
                return "false";
            } else {
                return hyphenVat;
            }
        }

        /**
         * Sets the value of the hyphenVat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHyphenVat(String value) {
            this.hyphenVat = value;
        }

        /**
         * Gets the value of the subtotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSubtotal() {
            return subtotal;
        }

        /**
         * Sets the value of the subtotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSubtotal(BigDecimal value) {
            this.subtotal = value;
        }

        /**
         * Gets the value of the hyphenSubtotal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHyphenSubtotal() {
            if (hyphenSubtotal == null) {
                return "false";
            } else {
                return hyphenSubtotal;
            }
        }

        /**
         * Sets the value of the hyphenSubtotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHyphenSubtotal(String value) {
            this.hyphenSubtotal = value;
        }

        /**
         * Gets the value of the itemMark property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getItemMark() {
            return itemMark;
        }

        /**
         * Sets the value of the itemMark property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setItemMark(BigInteger value) {
            this.itemMark = value;
        }

        /**
         * Gets the value of the additionalProperty property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdditionalProperty() {
            return additionalProperty;
        }

        /**
         * Sets the value of the additionalProperty property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdditionalProperty(String value) {
            this.additionalProperty = value;
        }

        /**
         * Gets the value of the itemVendorCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemVendorCode() {
            return itemVendorCode;
        }

        /**
         * Sets the value of the itemVendorCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemVendorCode(String value) {
            this.itemVendorCode = value;
        }

        /**
         * Gets the value of the itemToRelease property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getItemToRelease() {
            return itemToRelease;
        }

        /**
         * Sets the value of the itemToRelease property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItemToRelease(BigDecimal value) {
            this.itemToRelease = value;
        }

        /**
         * Gets the value of the itemCharact property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemCharact() {
            return itemCharact;
        }

        /**
         * Sets the value of the itemCharact property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemCharact(String value) {
            this.itemCharact = value;
        }

        /**
         * Gets the value of the itemArticle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemArticle() {
            return itemArticle;
        }

        /**
         * Sets the value of the itemArticle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemArticle(String value) {
            this.itemArticle = value;
        }

        /**
         * Gets the value of the itemKind property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemKind() {
            return itemKind;
        }

        /**
         * Sets the value of the itemKind property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemKind(String value) {
            this.itemKind = value;
        }

        /**
         * Gets the value of the catalogCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCatalogCode() {
            return catalogCode;
        }

        /**
         * Sets the value of the catalogCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCatalogCode(String value) {
            this.catalogCode = value;
        }

        /**
         * Gets the value of the itemTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemTypeCode() {
            return itemTypeCode;
        }

        /**
         * Sets the value of the itemTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemTypeCode(String value) {
            this.itemTypeCode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="AdditionalInfo" type="{}AdditionalInfo" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "additionalInfo"
        })
        public static class AdditionalInfos {

            @XmlElement(name = "AdditionalInfo", required = true)
            protected List<AdditionalInfo> additionalInfo;

            /**
             * Gets the value of the additionalInfo property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the additionalInfo property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAdditionalInfo().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AdditionalInfo }
             * 
             * 
             */
            public List<AdditionalInfo> getAdditionalInfo() {
                if (additionalInfo == null) {
                    additionalInfo = new ArrayList<AdditionalInfo>();
                }
                return this.additionalInfo;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="CustomsDeclaration" type="{}CustomsDeclarationWithHyphens" maxOccurs="unbounded" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "customsDeclaration"
        })
        public static class CustomsDeclarations {

            @XmlElement(name = "CustomsDeclaration")
            protected List<CustomsDeclarationWithHyphens> customsDeclaration;

            /**
             * Gets the value of the customsDeclaration property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the customsDeclaration property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCustomsDeclaration().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CustomsDeclarationWithHyphens }
             * 
             * 
             */
            public List<CustomsDeclarationWithHyphens> getCustomsDeclaration() {
                if (customsDeclaration == null) {
                    customsDeclaration = new ArrayList<CustomsDeclarationWithHyphens>();
                }
                return this.customsDeclaration;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ItemIdentificationNumber" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;choice&gt;
         *                   &lt;element name="Unit" type="{}string255" maxOccurs="unbounded" minOccurs="0"/&gt;
         *                   &lt;element name="PackageId" type="{}string255" maxOccurs="unbounded" minOccurs="0"/&gt;
         *                 &lt;/choice&gt;
         *                 &lt;attribute name="TransPackageId" type="{}string255" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "itemIdentificationNumber"
        })
        public static class ItemIdentificationNumbers {

            @XmlElement(name = "ItemIdentificationNumber", required = true)
            protected List<InvoiceTable.Item.ItemIdentificationNumbers.ItemIdentificationNumber> itemIdentificationNumber;

            /**
             * Gets the value of the itemIdentificationNumber property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the itemIdentificationNumber property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItemIdentificationNumber().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link InvoiceTable.Item.ItemIdentificationNumbers.ItemIdentificationNumber }
             * 
             * 
             */
            public List<InvoiceTable.Item.ItemIdentificationNumbers.ItemIdentificationNumber> getItemIdentificationNumber() {
                if (itemIdentificationNumber == null) {
                    itemIdentificationNumber = new ArrayList<InvoiceTable.Item.ItemIdentificationNumbers.ItemIdentificationNumber>();
                }
                return this.itemIdentificationNumber;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;choice&gt;
             *         &lt;element name="Unit" type="{}string255" maxOccurs="unbounded" minOccurs="0"/&gt;
             *         &lt;element name="PackageId" type="{}string255" maxOccurs="unbounded" minOccurs="0"/&gt;
             *       &lt;/choice&gt;
             *       &lt;attribute name="TransPackageId" type="{}string255" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "unit",
                "packageId"
            })
            public static class ItemIdentificationNumber {

                @XmlElement(name = "Unit")
                protected List<String> unit;
                @XmlElement(name = "PackageId")
                protected List<String> packageId;
                @XmlAttribute(name = "TransPackageId")
                protected String transPackageId;

                /**
                 * Gets the value of the unit property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the unit property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getUnit().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getUnit() {
                    if (unit == null) {
                        unit = new ArrayList<String>();
                    }
                    return this.unit;
                }

                /**
                 * Gets the value of the packageId property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the packageId property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPackageId().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getPackageId() {
                    if (packageId == null) {
                        packageId = new ArrayList<String>();
                    }
                    return this.packageId;
                }

                /**
                 * Gets the value of the transPackageId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTransPackageId() {
                    return transPackageId;
                }

                /**
                 * Sets the value of the transPackageId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTransPackageId(String value) {
                    this.transPackageId = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ItemTracingInfo" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="RegNumberUnit" use="required" type="{}string29" /&gt;
         *                 &lt;attribute name="Unit" use="required" type="{}okei" /&gt;
         *                 &lt;attribute name="Quantity" use="required"&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
         *                       &lt;totalDigits value="26"/&gt;
         *                       &lt;fractionDigits value="11"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/attribute&gt;
         *                 &lt;attribute name="ItemAddInfo" type="{}string255" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "itemTracingInfo"
        })
        public static class ItemTracingInfos {

            @XmlElement(name = "ItemTracingInfo", required = true)
            protected List<InvoiceTable.Item.ItemTracingInfos.ItemTracingInfo> itemTracingInfo;

            /**
             * Gets the value of the itemTracingInfo property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the itemTracingInfo property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItemTracingInfo().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link InvoiceTable.Item.ItemTracingInfos.ItemTracingInfo }
             * 
             * 
             */
            public List<InvoiceTable.Item.ItemTracingInfos.ItemTracingInfo> getItemTracingInfo() {
                if (itemTracingInfo == null) {
                    itemTracingInfo = new ArrayList<InvoiceTable.Item.ItemTracingInfos.ItemTracingInfo>();
                }
                return this.itemTracingInfo;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="RegNumberUnit" use="required" type="{}string29" /&gt;
             *       &lt;attribute name="Unit" use="required" type="{}okei" /&gt;
             *       &lt;attribute name="Quantity" use="required"&gt;
             *         &lt;simpleType&gt;
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
             *             &lt;totalDigits value="26"/&gt;
             *             &lt;fractionDigits value="11"/&gt;
             *           &lt;/restriction&gt;
             *         &lt;/simpleType&gt;
             *       &lt;/attribute&gt;
             *       &lt;attribute name="ItemAddInfo" type="{}string255" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ItemTracingInfo {

                @XmlAttribute(name = "RegNumberUnit", required = true)
                protected String regNumberUnit;
                @XmlAttribute(name = "Unit", required = true)
                protected String unit;
                @XmlAttribute(name = "Quantity", required = true)
                protected BigDecimal quantity;
                @XmlAttribute(name = "ItemAddInfo")
                protected String itemAddInfo;

                /**
                 * Gets the value of the regNumberUnit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRegNumberUnit() {
                    return regNumberUnit;
                }

                /**
                 * Sets the value of the regNumberUnit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRegNumberUnit(String value) {
                    this.regNumberUnit = value;
                }

                /**
                 * Gets the value of the unit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUnit() {
                    return unit;
                }

                /**
                 * Sets the value of the unit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUnit(String value) {
                    this.unit = value;
                }

                /**
                 * Gets the value of the quantity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getQuantity() {
                    return quantity;
                }

                /**
                 * Sets the value of the quantity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setQuantity(BigDecimal value) {
                    this.quantity = value;
                }

                /**
                 * Gets the value of the itemAddInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getItemAddInfo() {
                    return itemAddInfo;
                }

                /**
                 * Sets the value of the itemAddInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setItemAddInfo(String value) {
                    this.itemAddInfo = value;
                }

            }

        }

    }

}
