//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.29 at 01:59:19 PM MSK 
//


package ru.grinn.diadocsoap.xjs;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.grinn.diadocsoap.xjs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.grinn.diadocsoap.xjs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens }
     * 
     */
    public UniversalTransferDocumentWithHyphens createUniversalTransferDocumentWithHyphens() {
        return new UniversalTransferDocumentWithHyphens();
    }

    /**
     * Create an instance of {@link OutgoingUniversalTransferDocument }
     * 
     */
    public OutgoingUniversalTransferDocument createOutgoingUniversalTransferDocument() {
        return new OutgoingUniversalTransferDocument();
    }

    /**
     * Create an instance of {@link Waybills }
     * 
     */
    public Waybills createWaybills() {
        return new Waybills();
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens.DocumentShipments }
     * 
     */
    public UniversalTransferDocumentWithHyphens.DocumentShipments createUniversalTransferDocumentWithHyphensDocumentShipments() {
        return new UniversalTransferDocumentWithHyphens.DocumentShipments();
    }

    /**
     * Create an instance of {@link TransferInfo }
     * 
     */
    public TransferInfo createTransferInfo() {
        return new TransferInfo();
    }

    /**
     * Create an instance of {@link InvoiceTable }
     * 
     */
    public InvoiceTable createInvoiceTable() {
        return new InvoiceTable();
    }

    /**
     * Create an instance of {@link InvoiceTable.Item }
     * 
     */
    public InvoiceTable.Item createInvoiceTableItem() {
        return new InvoiceTable.Item();
    }

    /**
     * Create an instance of {@link InvoiceTable.Item.ItemIdentificationNumbers }
     * 
     */
    public InvoiceTable.Item.ItemIdentificationNumbers createInvoiceTableItemItemIdentificationNumbers() {
        return new InvoiceTable.Item.ItemIdentificationNumbers();
    }

    /**
     * Create an instance of {@link InvoiceTable.Item.ItemTracingInfos }
     * 
     */
    public InvoiceTable.Item.ItemTracingInfos createInvoiceTableItemItemTracingInfos() {
        return new InvoiceTable.Item.ItemTracingInfos();
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens.Shippers }
     * 
     */
    public UniversalTransferDocumentWithHyphens.Shippers createUniversalTransferDocumentWithHyphensShippers() {
        return new UniversalTransferDocumentWithHyphens.Shippers();
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens.Sellers }
     * 
     */
    public UniversalTransferDocumentWithHyphens.Sellers createUniversalTransferDocumentWithHyphensSellers() {
        return new UniversalTransferDocumentWithHyphens.Sellers();
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens.Buyers }
     * 
     */
    public UniversalTransferDocumentWithHyphens.Buyers createUniversalTransferDocumentWithHyphensBuyers() {
        return new UniversalTransferDocumentWithHyphens.Buyers();
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens.Consignees }
     * 
     */
    public UniversalTransferDocumentWithHyphens.Consignees createUniversalTransferDocumentWithHyphensConsignees() {
        return new UniversalTransferDocumentWithHyphens.Consignees();
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens.Signers }
     * 
     */
    public UniversalTransferDocumentWithHyphens.Signers createUniversalTransferDocumentWithHyphensSigners() {
        return new UniversalTransferDocumentWithHyphens.Signers();
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens.PaymentDocuments }
     * 
     */
    public UniversalTransferDocumentWithHyphens.PaymentDocuments createUniversalTransferDocumentWithHyphensPaymentDocuments() {
        return new UniversalTransferDocumentWithHyphens.PaymentDocuments();
    }

    /**
     * Create an instance of {@link AdditionalInfoId }
     * 
     */
    public AdditionalInfoId createAdditionalInfoId() {
        return new AdditionalInfoId();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationInfoWithHyphens }
     * 
     */
    public ExtendedOrganizationInfoWithHyphens createExtendedOrganizationInfoWithHyphens() {
        return new ExtendedOrganizationInfoWithHyphens();
    }

    /**
     * Create an instance of {@link TransferBase820 }
     * 
     */
    public TransferBase820 createTransferBase820() {
        return new TransferBase820();
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens.SellerInfoCircumPublicProc }
     * 
     */
    public UniversalTransferDocumentWithHyphens.SellerInfoCircumPublicProc createUniversalTransferDocumentWithHyphensSellerInfoCircumPublicProc() {
        return new UniversalTransferDocumentWithHyphens.SellerInfoCircumPublicProc();
    }

    /**
     * Create an instance of {@link AdditionalInfoId736 }
     * 
     */
    public AdditionalInfoId736 createAdditionalInfoId736() {
        return new AdditionalInfoId736();
    }

    /**
     * Create an instance of {@link AdditionalInfo }
     * 
     */
    public AdditionalInfo createAdditionalInfo() {
        return new AdditionalInfo();
    }

    /**
     * Create an instance of {@link CustomsDeclaration }
     * 
     */
    public CustomsDeclaration createCustomsDeclaration() {
        return new CustomsDeclaration();
    }

    /**
     * Create an instance of {@link CustomsDeclarationWithHyphens }
     * 
     */
    public CustomsDeclarationWithHyphens createCustomsDeclarationWithHyphens() {
        return new CustomsDeclarationWithHyphens();
    }

    /**
     * Create an instance of {@link InvoiceTotalsDiff }
     * 
     */
    public InvoiceTotalsDiff createInvoiceTotalsDiff() {
        return new InvoiceTotalsDiff();
    }

    /**
     * Create an instance of {@link InvoiceTotalsDiff736 }
     * 
     */
    public InvoiceTotalsDiff736 createInvoiceTotalsDiff736() {
        return new InvoiceTotalsDiff736();
    }

    /**
     * Create an instance of {@link InvoiceItemAmountsDiff }
     * 
     */
    public InvoiceItemAmountsDiff createInvoiceItemAmountsDiff() {
        return new InvoiceItemAmountsDiff();
    }

    /**
     * Create an instance of {@link CorrectableInvoiceItemFieldsWithoutTaxRate }
     * 
     */
    public CorrectableInvoiceItemFieldsWithoutTaxRate createCorrectableInvoiceItemFieldsWithoutTaxRate() {
        return new CorrectableInvoiceItemFieldsWithoutTaxRate();
    }

    /**
     * Create an instance of {@link CorrectableInvoiceItemFields }
     * 
     */
    public CorrectableInvoiceItemFields createCorrectableInvoiceItemFields() {
        return new CorrectableInvoiceItemFields();
    }

    /**
     * Create an instance of {@link CorrectableInvoiceItemFieldsWithTwentyPercent }
     * 
     */
    public CorrectableInvoiceItemFieldsWithTwentyPercent createCorrectableInvoiceItemFieldsWithTwentyPercent() {
        return new CorrectableInvoiceItemFieldsWithTwentyPercent();
    }

    /**
     * Create an instance of {@link CorrectableInvoiceItemFieldsWithTaxedByAgent }
     * 
     */
    public CorrectableInvoiceItemFieldsWithTaxedByAgent createCorrectableInvoiceItemFieldsWithTaxedByAgent() {
        return new CorrectableInvoiceItemFieldsWithTaxedByAgent();
    }

    /**
     * Create an instance of {@link CorrectableInvoiceItemFieldsWithTwentyPercentAndTaxedByAgent }
     * 
     */
    public CorrectableInvoiceItemFieldsWithTwentyPercentAndTaxedByAgent createCorrectableInvoiceItemFieldsWithTwentyPercentAndTaxedByAgent() {
        return new CorrectableInvoiceItemFieldsWithTwentyPercentAndTaxedByAgent();
    }

    /**
     * Create an instance of {@link Attorney }
     * 
     */
    public Attorney createAttorney() {
        return new Attorney();
    }

    /**
     * Create an instance of {@link Official }
     * 
     */
    public Official createOfficial() {
        return new Official();
    }

    /**
     * Create an instance of {@link AcceptanceCertificateSignatureInfo }
     * 
     */
    public AcceptanceCertificateSignatureInfo createAcceptanceCertificateSignatureInfo() {
        return new AcceptanceCertificateSignatureInfo();
    }

    /**
     * Create an instance of {@link PaymentDocumentInfo }
     * 
     */
    public PaymentDocumentInfo createPaymentDocumentInfo() {
        return new PaymentDocumentInfo();
    }

    /**
     * Create an instance of {@link GroundInfo }
     * 
     */
    public GroundInfo createGroundInfo() {
        return new GroundInfo();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationInfo }
     * 
     */
    public ExtendedOrganizationInfo createExtendedOrganizationInfo() {
        return new ExtendedOrganizationInfo();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationInfoForeignAddress1000 }
     * 
     */
    public ExtendedOrganizationInfoForeignAddress1000 createExtendedOrganizationInfoForeignAddress1000() {
        return new ExtendedOrganizationInfoForeignAddress1000();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationInfoTorg2 }
     * 
     */
    public ExtendedOrganizationInfoTorg2 createExtendedOrganizationInfoTorg2() {
        return new ExtendedOrganizationInfoTorg2();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationDetails }
     * 
     */
    public ExtendedOrganizationDetails createExtendedOrganizationDetails() {
        return new ExtendedOrganizationDetails();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationDetailsForeignAddress1000 }
     * 
     */
    public ExtendedOrganizationDetailsForeignAddress1000 createExtendedOrganizationDetailsForeignAddress1000() {
        return new ExtendedOrganizationDetailsForeignAddress1000();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationDetailsTorg2 }
     * 
     */
    public ExtendedOrganizationDetailsTorg2 createExtendedOrganizationDetailsTorg2() {
        return new ExtendedOrganizationDetailsTorg2();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationReference }
     * 
     */
    public ExtendedOrganizationReference createExtendedOrganizationReference() {
        return new ExtendedOrganizationReference();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationDetailsManualFilling }
     * 
     */
    public ExtendedOrganizationDetailsManualFilling createExtendedOrganizationDetailsManualFilling() {
        return new ExtendedOrganizationDetailsManualFilling();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationDetailsManualFillingTorg2 }
     * 
     */
    public ExtendedOrganizationDetailsManualFillingTorg2 createExtendedOrganizationDetailsManualFillingTorg2() {
        return new ExtendedOrganizationDetailsManualFillingTorg2();
    }

    /**
     * Create an instance of {@link ExtendedOrganizationDetailsWithHyphens }
     * 
     */
    public ExtendedOrganizationDetailsWithHyphens createExtendedOrganizationDetailsWithHyphens() {
        return new ExtendedOrganizationDetailsWithHyphens();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AddressForeignAddress1000 }
     * 
     */
    public AddressForeignAddress1000 createAddressForeignAddress1000() {
        return new AddressForeignAddress1000();
    }

    /**
     * Create an instance of {@link RussianAddress }
     * 
     */
    public RussianAddress createRussianAddress() {
        return new RussianAddress();
    }

    /**
     * Create an instance of {@link ForeignAddress }
     * 
     */
    public ForeignAddress createForeignAddress() {
        return new ForeignAddress();
    }

    /**
     * Create an instance of {@link ForeignAddress1000 }
     * 
     */
    public ForeignAddress1000 createForeignAddress1000() {
        return new ForeignAddress1000();
    }

    /**
     * Create an instance of {@link SignerInfo }
     * 
     */
    public SignerInfo createSignerInfo() {
        return new SignerInfo();
    }

    /**
     * Create an instance of {@link SignerDetails }
     * 
     */
    public SignerDetails createSignerDetails() {
        return new SignerDetails();
    }

    /**
     * Create an instance of {@link SignerReferenceInfo }
     * 
     */
    public SignerReferenceInfo createSignerReferenceInfo() {
        return new SignerReferenceInfo();
    }

    /**
     * Create an instance of {@link SignerReference }
     * 
     */
    public SignerReference createSignerReference() {
        return new SignerReference();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetailsBase }
     * 
     */
    public ExtendedSignerDetailsBase createExtendedSignerDetailsBase() {
        return new ExtendedSignerDetailsBase();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetailsBase736 }
     * 
     */
    public ExtendedSignerDetailsBase736 createExtendedSignerDetailsBase736() {
        return new ExtendedSignerDetailsBase736();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetails }
     * 
     */
    public ExtendedSignerDetails createExtendedSignerDetails() {
        return new ExtendedSignerDetails();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetails736 }
     * 
     */
    public ExtendedSignerDetails736 createExtendedSignerDetails736() {
        return new ExtendedSignerDetails736();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetailsSellerTitle }
     * 
     */
    public ExtendedSignerDetailsSellerTitle createExtendedSignerDetailsSellerTitle() {
        return new ExtendedSignerDetailsSellerTitle();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetailsBuyerTitle }
     * 
     */
    public ExtendedSignerDetailsBuyerTitle createExtendedSignerDetailsBuyerTitle() {
        return new ExtendedSignerDetailsBuyerTitle();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetailsBuyerTitle820 }
     * 
     */
    public ExtendedSignerDetailsBuyerTitle820 createExtendedSignerDetailsBuyerTitle820() {
        return new ExtendedSignerDetailsBuyerTitle820();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetailsCorrectionSellerTitle }
     * 
     */
    public ExtendedSignerDetailsCorrectionSellerTitle createExtendedSignerDetailsCorrectionSellerTitle() {
        return new ExtendedSignerDetailsCorrectionSellerTitle();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetailsCorrectionBuyerTitle }
     * 
     */
    public ExtendedSignerDetailsCorrectionBuyerTitle createExtendedSignerDetailsCorrectionBuyerTitle() {
        return new ExtendedSignerDetailsCorrectionBuyerTitle();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetailsCorrectionBuyerTitle736 }
     * 
     */
    public ExtendedSignerDetailsCorrectionBuyerTitle736 createExtendedSignerDetailsCorrectionBuyerTitle736() {
        return new ExtendedSignerDetailsCorrectionBuyerTitle736();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetails551552 }
     * 
     */
    public ExtendedSignerDetails551552 createExtendedSignerDetails551552() {
        return new ExtendedSignerDetails551552();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetailsTorg2Buyer }
     * 
     */
    public ExtendedSignerDetailsTorg2Buyer createExtendedSignerDetailsTorg2Buyer() {
        return new ExtendedSignerDetailsTorg2Buyer();
    }

    /**
     * Create an instance of {@link ExtendedSignerDetailsTorg2AdditionalInfo }
     * 
     */
    public ExtendedSignerDetailsTorg2AdditionalInfo createExtendedSignerDetailsTorg2AdditionalInfo() {
        return new ExtendedSignerDetailsTorg2AdditionalInfo();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
        return new Employee();
    }

    /**
     * Create an instance of {@link OtherIssuer }
     * 
     */
    public OtherIssuer createOtherIssuer() {
        return new OtherIssuer();
    }

    /**
     * Create an instance of {@link TransferBase }
     * 
     */
    public TransferBase createTransferBase() {
        return new TransferBase();
    }

    /**
     * Create an instance of {@link SendOutgoingUniversalTransferDocumentRequest }
     * 
     */
    public SendOutgoingUniversalTransferDocumentRequest createSendOutgoingUniversalTransferDocumentRequest() {
        return new SendOutgoingUniversalTransferDocumentRequest();
    }

    /**
     * Create an instance of {@link SendOutgoingUniversalTransferDocumentResponse }
     * 
     */
    public SendOutgoingUniversalTransferDocumentResponse createSendOutgoingUniversalTransferDocumentResponse() {
        return new SendOutgoingUniversalTransferDocumentResponse();
    }

    /**
     * Create an instance of {@link OutgoingUniversalTransferDocumentFirm }
     * 
     */
    public OutgoingUniversalTransferDocumentFirm createOutgoingUniversalTransferDocumentFirm() {
        return new OutgoingUniversalTransferDocumentFirm();
    }

    /**
     * Create an instance of {@link OutgoingUniversalTransferDocumentFirmAddress }
     * 
     */
    public OutgoingUniversalTransferDocumentFirmAddress createOutgoingUniversalTransferDocumentFirmAddress() {
        return new OutgoingUniversalTransferDocumentFirmAddress();
    }

    /**
     * Create an instance of {@link OutgoingUniversalTransferDocumentItem }
     * 
     */
    public OutgoingUniversalTransferDocumentItem createOutgoingUniversalTransferDocumentItem() {
        return new OutgoingUniversalTransferDocumentItem();
    }

    /**
     * Create an instance of {@link OutgoingUniversalTransferDocument.Items }
     * 
     */
    public OutgoingUniversalTransferDocument.Items createOutgoingUniversalTransferDocumentItems() {
        return new OutgoingUniversalTransferDocument.Items();
    }

    /**
     * Create an instance of {@link Waybills.Waybill }
     * 
     */
    public Waybills.Waybill createWaybillsWaybill() {
        return new Waybills.Waybill();
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens.DocumentShipments.DocumentShipment }
     * 
     */
    public UniversalTransferDocumentWithHyphens.DocumentShipments.DocumentShipment createUniversalTransferDocumentWithHyphensDocumentShipmentsDocumentShipment() {
        return new UniversalTransferDocumentWithHyphens.DocumentShipments.DocumentShipment();
    }

    /**
     * Create an instance of {@link TransferInfo.TransferBases }
     * 
     */
    public TransferInfo.TransferBases createTransferInfoTransferBases() {
        return new TransferInfo.TransferBases();
    }

    /**
     * Create an instance of {@link InvoiceTable.Item.CustomsDeclarations }
     * 
     */
    public InvoiceTable.Item.CustomsDeclarations createInvoiceTableItemCustomsDeclarations() {
        return new InvoiceTable.Item.CustomsDeclarations();
    }

    /**
     * Create an instance of {@link InvoiceTable.Item.AdditionalInfos }
     * 
     */
    public InvoiceTable.Item.AdditionalInfos createInvoiceTableItemAdditionalInfos() {
        return new InvoiceTable.Item.AdditionalInfos();
    }

    /**
     * Create an instance of {@link InvoiceTable.Item.ItemIdentificationNumbers.ItemIdentificationNumber }
     * 
     */
    public InvoiceTable.Item.ItemIdentificationNumbers.ItemIdentificationNumber createInvoiceTableItemItemIdentificationNumbersItemIdentificationNumber() {
        return new InvoiceTable.Item.ItemIdentificationNumbers.ItemIdentificationNumber();
    }

    /**
     * Create an instance of {@link InvoiceTable.Item.ItemTracingInfos.ItemTracingInfo }
     * 
     */
    public InvoiceTable.Item.ItemTracingInfos.ItemTracingInfo createInvoiceTableItemItemTracingInfosItemTracingInfo() {
        return new InvoiceTable.Item.ItemTracingInfos.ItemTracingInfo();
    }

    /**
     * Create an instance of {@link UniversalTransferDocumentWithHyphens.Shippers.Shipper }
     * 
     */
    public UniversalTransferDocumentWithHyphens.Shippers.Shipper createUniversalTransferDocumentWithHyphensShippersShipper() {
        return new UniversalTransferDocumentWithHyphens.Shippers.Shipper();
    }

}
