//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.28 at 06:02:11 PM MSK 
//


package ru.grinn.diadocsoap.xjs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutgoingUniversalTransferDocumentFirm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutgoingUniversalTransferDocumentFirm"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="INN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="KPP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Address" type="{http://www.grinn-corp.ru/gestori/edo}OutgoingUniversalTransferDocumentFirmAddress"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutgoingUniversalTransferDocumentFirm", namespace = "http://www.grinn-corp.ru/gestori/edo", propOrder = {
    "inn",
    "kpp",
    "name",
    "address"
})
public class OutgoingUniversalTransferDocumentFirm {

    @XmlElement(name = "INN", namespace = "http://www.grinn-corp.ru/gestori/edo", required = true)
    protected String inn;
    @XmlElement(name = "KPP", namespace = "http://www.grinn-corp.ru/gestori/edo", required = true)
    protected String kpp;
    @XmlElement(name = "Name", namespace = "http://www.grinn-corp.ru/gestori/edo", required = true)
    protected String name;
    @XmlElement(name = "Address", namespace = "http://www.grinn-corp.ru/gestori/edo", required = true)
    protected OutgoingUniversalTransferDocumentFirmAddress address;

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINN() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINN(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the kpp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKPP() {
        return kpp;
    }

    /**
     * Sets the value of the kpp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKPP(String value) {
        this.kpp = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link OutgoingUniversalTransferDocumentFirmAddress }
     *     
     */
    public OutgoingUniversalTransferDocumentFirmAddress getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutgoingUniversalTransferDocumentFirmAddress }
     *     
     */
    public void setAddress(OutgoingUniversalTransferDocumentFirmAddress value) {
        this.address = value;
    }

}
