//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.29 at 01:59:19 PM MSK 
//


package ru.grinn.diadocsoap.xjs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransferInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransferInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="TransferBases" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TransferBase" type="{}TransferBase820" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Waybills" type="{}Waybills" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalInfoId" type="{}AdditionalInfoId" minOccurs="0"/&gt;
 *         &lt;element name="Carrier" type="{}ExtendedOrganizationInfoWithHyphens" minOccurs="0"/&gt;
 *         &lt;element name="Employee" type="{}Employee" minOccurs="0"/&gt;
 *         &lt;element name="OtherIssuer" type="{}OtherIssuer" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="OperationInfo" use="required" type="{}string255" /&gt;
 *       &lt;attribute name="OperationType" type="{}string255" /&gt;
 *       &lt;attribute name="TransferDate" type="{}date" /&gt;
 *       &lt;attribute name="TransferStartDate" type="{}date" /&gt;
 *       &lt;attribute name="TransferEndDate" type="{}date" /&gt;
 *       &lt;attribute name="TransferTextInfo" type="{}string1000" /&gt;
 *       &lt;attribute name="CreatedThingTransferDate" type="{}date" /&gt;
 *       &lt;attribute name="CreatedThingInfo" type="{}string1000" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransferInfo", propOrder = {

})
public class TransferInfo {

    @XmlElement(name = "TransferBases")
    protected TransferInfo.TransferBases transferBases;
    @XmlElement(name = "Waybills")
    protected Waybills waybills;
    @XmlElement(name = "AdditionalInfoId")
    protected AdditionalInfoId additionalInfoId;
    @XmlElement(name = "Carrier")
    protected ExtendedOrganizationInfoWithHyphens carrier;
    @XmlElement(name = "Employee")
    protected Employee employee;
    @XmlElement(name = "OtherIssuer")
    protected OtherIssuer otherIssuer;
    @XmlAttribute(name = "OperationInfo", required = true)
    protected String operationInfo;
    @XmlAttribute(name = "OperationType")
    protected String operationType;
    @XmlAttribute(name = "TransferDate")
    protected String transferDate;
    @XmlAttribute(name = "TransferStartDate")
    protected String transferStartDate;
    @XmlAttribute(name = "TransferEndDate")
    protected String transferEndDate;
    @XmlAttribute(name = "TransferTextInfo")
    protected String transferTextInfo;
    @XmlAttribute(name = "CreatedThingTransferDate")
    protected String createdThingTransferDate;
    @XmlAttribute(name = "CreatedThingInfo")
    protected String createdThingInfo;

    /**
     * Gets the value of the transferBases property.
     * 
     * @return
     *     possible object is
     *     {@link TransferInfo.TransferBases }
     *     
     */
    public TransferInfo.TransferBases getTransferBases() {
        return transferBases;
    }

    /**
     * Sets the value of the transferBases property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferInfo.TransferBases }
     *     
     */
    public void setTransferBases(TransferInfo.TransferBases value) {
        this.transferBases = value;
    }

    /**
     * Gets the value of the waybills property.
     * 
     * @return
     *     possible object is
     *     {@link Waybills }
     *     
     */
    public Waybills getWaybills() {
        return waybills;
    }

    /**
     * Sets the value of the waybills property.
     * 
     * @param value
     *     allowed object is
     *     {@link Waybills }
     *     
     */
    public void setWaybills(Waybills value) {
        this.waybills = value;
    }

    /**
     * Gets the value of the additionalInfoId property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInfoId }
     *     
     */
    public AdditionalInfoId getAdditionalInfoId() {
        return additionalInfoId;
    }

    /**
     * Sets the value of the additionalInfoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInfoId }
     *     
     */
    public void setAdditionalInfoId(AdditionalInfoId value) {
        this.additionalInfoId = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link ExtendedOrganizationInfoWithHyphens }
     *     
     */
    public ExtendedOrganizationInfoWithHyphens getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtendedOrganizationInfoWithHyphens }
     *     
     */
    public void setCarrier(ExtendedOrganizationInfoWithHyphens value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the employee property.
     * 
     * @return
     *     possible object is
     *     {@link Employee }
     *     
     */
    public Employee getEmployee() {
        return employee;
    }

    /**
     * Sets the value of the employee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employee }
     *     
     */
    public void setEmployee(Employee value) {
        this.employee = value;
    }

    /**
     * Gets the value of the otherIssuer property.
     * 
     * @return
     *     possible object is
     *     {@link OtherIssuer }
     *     
     */
    public OtherIssuer getOtherIssuer() {
        return otherIssuer;
    }

    /**
     * Sets the value of the otherIssuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherIssuer }
     *     
     */
    public void setOtherIssuer(OtherIssuer value) {
        this.otherIssuer = value;
    }

    /**
     * Gets the value of the operationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationInfo() {
        return operationInfo;
    }

    /**
     * Sets the value of the operationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationInfo(String value) {
        this.operationInfo = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the transferDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferDate() {
        return transferDate;
    }

    /**
     * Sets the value of the transferDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferDate(String value) {
        this.transferDate = value;
    }

    /**
     * Gets the value of the transferStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferStartDate() {
        return transferStartDate;
    }

    /**
     * Sets the value of the transferStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferStartDate(String value) {
        this.transferStartDate = value;
    }

    /**
     * Gets the value of the transferEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferEndDate() {
        return transferEndDate;
    }

    /**
     * Sets the value of the transferEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferEndDate(String value) {
        this.transferEndDate = value;
    }

    /**
     * Gets the value of the transferTextInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferTextInfo() {
        return transferTextInfo;
    }

    /**
     * Sets the value of the transferTextInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferTextInfo(String value) {
        this.transferTextInfo = value;
    }

    /**
     * Gets the value of the createdThingTransferDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedThingTransferDate() {
        return createdThingTransferDate;
    }

    /**
     * Sets the value of the createdThingTransferDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedThingTransferDate(String value) {
        this.createdThingTransferDate = value;
    }

    /**
     * Gets the value of the createdThingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedThingInfo() {
        return createdThingInfo;
    }

    /**
     * Sets the value of the createdThingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedThingInfo(String value) {
        this.createdThingInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TransferBase" type="{}TransferBase820" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transferBase"
    })
    public static class TransferBases {

        @XmlElement(name = "TransferBase", required = true)
        protected List<TransferBase820> transferBase;

        /**
         * Gets the value of the transferBase property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transferBase property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransferBase().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TransferBase820 }
         * 
         * 
         */
        public List<TransferBase820> getTransferBase() {
            if (transferBase == null) {
                transferBase = new ArrayList<TransferBase820>();
            }
            return this.transferBase;
        }

    }

}
