//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.30 at 11:18:19 AM MSK 
//


package ru.grinn.diadocsoap.xjs;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Sellers"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Seller" type="{}ExtendedOrganizationInfoWithHyphens" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Buyers"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Buyer" type="{}ExtendedOrganizationInfoWithHyphens" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Shippers" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Shipper" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice minOccurs="0"&gt;
 *                             &lt;element name="OrganizationDetails" type="{}ExtendedOrganizationDetailsWithHyphens"/&gt;
 *                             &lt;element name="OrganizationReference" type="{}ExtendedOrganizationReference"/&gt;
 *                           &lt;/choice&gt;
 *                           &lt;attribute name="SameAsSeller" default="false"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;enumeration value="true"/&gt;
 *                                 &lt;enumeration value="false"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Consignees" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Consignee" type="{}ExtendedOrganizationInfoWithHyphens" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Signers"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded"&gt;
 *                   &lt;element name="SignerReference" type="{}SignerReference"/&gt;
 *                   &lt;element name="SignerDetails" type="{}ExtendedSignerDetails_SellerTitle"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PaymentDocuments" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Document" type="{}PaymentDocumentInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AdditionalInfoId" type="{}AdditionalInfoId" minOccurs="0"/&gt;
 *         &lt;element name="Table" type="{}InvoiceTable" minOccurs="0"/&gt;
 *         &lt;element name="TransferInfo" type="{}TransferInfo" minOccurs="0"/&gt;
 *         &lt;element name="FactorInfo" type="{}ExtendedOrganizationInfoWithHyphens" minOccurs="0"/&gt;
 *         &lt;element name="MainAssignMonetaryClaim" type="{}TransferBase820" minOccurs="0"/&gt;
 *         &lt;element name="SellerInfoCircumPublicProc" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="DateStateContract" use="required" type="{}date" /&gt;
 *                 &lt;attribute name="NumberStateContract" use="required" type="{}string100" /&gt;
 *                 &lt;attribute name="PersonalAccountSeller"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;length value="11"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="SellerBudjetClassCode" type="{}string20f" /&gt;
 *                 &lt;attribute name="SellerTargetCode" type="{}string20f" /&gt;
 *                 &lt;attribute name="SellerTreasuryCode"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;minLength value="1"/&gt;
 *                       &lt;maxLength value="4"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="SellerTreasuryName" type="{}string2000" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DocumentShipments" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DocumentShipment" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Name" use="required" type="{}string255" /&gt;
 *                           &lt;attribute name="Number" use="required" type="{}string255" /&gt;
 *                           &lt;attribute name="Date" type="{}date" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="Function" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="СЧФ"/&gt;
 *             &lt;enumeration value="ДОП"/&gt;
 *             &lt;enumeration value="СЧФДОП"/&gt;
 *             &lt;enumeration value="СвРК"/&gt;
 *             &lt;enumeration value="СвЗК"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ApprovedStructureAdditionalInfoFields" type="{}string14f" /&gt;
 *       &lt;attribute name="SenderFnsParticipantId"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="4"/&gt;
 *             &lt;maxLength value="46"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="RecipientFnsParticipantId"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="4"/&gt;
 *             &lt;maxLength value="46"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="DocumentName" type="{}string255" /&gt;
 *       &lt;attribute name="DocumentDate" use="required" type="{}date" /&gt;
 *       &lt;attribute name="DocumentNumber" use="required" type="{}string1000" /&gt;
 *       &lt;attribute name="Currency" use="required" type="{}okv" /&gt;
 *       &lt;attribute name="CurrencyRate"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;totalDigits value="10"/&gt;
 *             &lt;fractionDigits value="4"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="RevisionDate" type="{}date" /&gt;
 *       &lt;attribute name="HyphenRevisionDate" default="false"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="RevisionNumber"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *             &lt;totalDigits value="3"/&gt;
 *             &lt;minInclusive value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="HyphenRevisionNumber" default="false"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="DocumentCreator" use="required" type="{}string1000" /&gt;
 *       &lt;attribute name="DocumentCreatorBase" type="{}string120" /&gt;
 *       &lt;attribute name="GovernmentContractInfo"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="20"/&gt;
 *             &lt;maxLength value="25"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="CircumFormatInvoice"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;length value="1"/&gt;
 *             &lt;enumeration value="1"/&gt;
 *             &lt;enumeration value="2"/&gt;
 *             &lt;enumeration value="3"/&gt;
 *             &lt;enumeration value="4"/&gt;
 *             &lt;enumeration value="5"/&gt;
 *             &lt;enumeration value="6"/&gt;
 *             &lt;enumeration value="7"/&gt;
 *             &lt;enumeration value="8"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "UniversalTransferDocumentWithHyphens")
public class UniversalTransferDocumentWithHyphens {

    @XmlElement(name = "Sellers", required = true)
    protected UniversalTransferDocumentWithHyphens.Sellers sellers;
    @XmlElement(name = "Buyers", required = true)
    protected UniversalTransferDocumentWithHyphens.Buyers buyers;
    @XmlElement(name = "Shippers")
    protected UniversalTransferDocumentWithHyphens.Shippers shippers;
    @XmlElement(name = "Consignees")
    protected UniversalTransferDocumentWithHyphens.Consignees consignees;
    @XmlElement(name = "Signers", required = true)
    protected UniversalTransferDocumentWithHyphens.Signers signers;
    @XmlElement(name = "PaymentDocuments")
    protected UniversalTransferDocumentWithHyphens.PaymentDocuments paymentDocuments;
    @XmlElement(name = "AdditionalInfoId")
    protected AdditionalInfoId additionalInfoId;
    @XmlElement(name = "Table")
    protected InvoiceTable table;
    @XmlElement(name = "TransferInfo")
    protected TransferInfo transferInfo;
    @XmlElement(name = "FactorInfo")
    protected ExtendedOrganizationInfoWithHyphens factorInfo;
    @XmlElement(name = "MainAssignMonetaryClaim")
    protected TransferBase820 mainAssignMonetaryClaim;
    @XmlElement(name = "SellerInfoCircumPublicProc")
    protected UniversalTransferDocumentWithHyphens.SellerInfoCircumPublicProc sellerInfoCircumPublicProc;
    @XmlElement(name = "DocumentShipments")
    protected UniversalTransferDocumentWithHyphens.DocumentShipments documentShipments;
    @XmlAttribute(name = "Function", required = true)
    protected String function;
    @XmlAttribute(name = "ApprovedStructureAdditionalInfoFields")
    protected String approvedStructureAdditionalInfoFields;
    @XmlAttribute(name = "SenderFnsParticipantId")
    protected String senderFnsParticipantId;
    @XmlAttribute(name = "RecipientFnsParticipantId")
    protected String recipientFnsParticipantId;
    @XmlAttribute(name = "DocumentName")
    protected String documentName;
    @XmlAttribute(name = "DocumentDate", required = true)
    protected String documentDate;
    @XmlAttribute(name = "DocumentNumber", required = true)
    protected String documentNumber;
    @XmlAttribute(name = "Currency", required = true)
    protected String currency;
    @XmlAttribute(name = "CurrencyRate")
    protected BigDecimal currencyRate;
    @XmlAttribute(name = "RevisionDate")
    protected String revisionDate;
    @XmlAttribute(name = "HyphenRevisionDate")
    protected String hyphenRevisionDate;
    @XmlAttribute(name = "RevisionNumber")
    protected BigInteger revisionNumber;
    @XmlAttribute(name = "HyphenRevisionNumber")
    protected String hyphenRevisionNumber;
    @XmlAttribute(name = "DocumentCreator", required = true)
    protected String documentCreator;
    @XmlAttribute(name = "DocumentCreatorBase")
    protected String documentCreatorBase;
    @XmlAttribute(name = "GovernmentContractInfo")
    protected String governmentContractInfo;
    @XmlAttribute(name = "CircumFormatInvoice")
    protected String circumFormatInvoice;

    /**
     * Gets the value of the sellers property.
     * 
     * @return
     *     possible object is
     *     {@link UniversalTransferDocumentWithHyphens.Sellers }
     *     
     */
    public UniversalTransferDocumentWithHyphens.Sellers getSellers() {
        return sellers;
    }

    /**
     * Sets the value of the sellers property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversalTransferDocumentWithHyphens.Sellers }
     *     
     */
    public void setSellers(UniversalTransferDocumentWithHyphens.Sellers value) {
        this.sellers = value;
    }

    /**
     * Gets the value of the buyers property.
     * 
     * @return
     *     possible object is
     *     {@link UniversalTransferDocumentWithHyphens.Buyers }
     *     
     */
    public UniversalTransferDocumentWithHyphens.Buyers getBuyers() {
        return buyers;
    }

    /**
     * Sets the value of the buyers property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversalTransferDocumentWithHyphens.Buyers }
     *     
     */
    public void setBuyers(UniversalTransferDocumentWithHyphens.Buyers value) {
        this.buyers = value;
    }

    /**
     * Gets the value of the shippers property.
     * 
     * @return
     *     possible object is
     *     {@link UniversalTransferDocumentWithHyphens.Shippers }
     *     
     */
    public UniversalTransferDocumentWithHyphens.Shippers getShippers() {
        return shippers;
    }

    /**
     * Sets the value of the shippers property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversalTransferDocumentWithHyphens.Shippers }
     *     
     */
    public void setShippers(UniversalTransferDocumentWithHyphens.Shippers value) {
        this.shippers = value;
    }

    /**
     * Gets the value of the consignees property.
     * 
     * @return
     *     possible object is
     *     {@link UniversalTransferDocumentWithHyphens.Consignees }
     *     
     */
    public UniversalTransferDocumentWithHyphens.Consignees getConsignees() {
        return consignees;
    }

    /**
     * Sets the value of the consignees property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversalTransferDocumentWithHyphens.Consignees }
     *     
     */
    public void setConsignees(UniversalTransferDocumentWithHyphens.Consignees value) {
        this.consignees = value;
    }

    /**
     * Gets the value of the signers property.
     * 
     * @return
     *     possible object is
     *     {@link UniversalTransferDocumentWithHyphens.Signers }
     *     
     */
    public UniversalTransferDocumentWithHyphens.Signers getSigners() {
        return signers;
    }

    /**
     * Sets the value of the signers property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversalTransferDocumentWithHyphens.Signers }
     *     
     */
    public void setSigners(UniversalTransferDocumentWithHyphens.Signers value) {
        this.signers = value;
    }

    /**
     * Gets the value of the paymentDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link UniversalTransferDocumentWithHyphens.PaymentDocuments }
     *     
     */
    public UniversalTransferDocumentWithHyphens.PaymentDocuments getPaymentDocuments() {
        return paymentDocuments;
    }

    /**
     * Sets the value of the paymentDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversalTransferDocumentWithHyphens.PaymentDocuments }
     *     
     */
    public void setPaymentDocuments(UniversalTransferDocumentWithHyphens.PaymentDocuments value) {
        this.paymentDocuments = value;
    }

    /**
     * Gets the value of the additionalInfoId property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInfoId }
     *     
     */
    public AdditionalInfoId getAdditionalInfoId() {
        return additionalInfoId;
    }

    /**
     * Sets the value of the additionalInfoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInfoId }
     *     
     */
    public void setAdditionalInfoId(AdditionalInfoId value) {
        this.additionalInfoId = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceTable }
     *     
     */
    public InvoiceTable getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceTable }
     *     
     */
    public void setTable(InvoiceTable value) {
        this.table = value;
    }

    /**
     * Gets the value of the transferInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TransferInfo }
     *     
     */
    public TransferInfo getTransferInfo() {
        return transferInfo;
    }

    /**
     * Sets the value of the transferInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferInfo }
     *     
     */
    public void setTransferInfo(TransferInfo value) {
        this.transferInfo = value;
    }

    /**
     * Gets the value of the factorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ExtendedOrganizationInfoWithHyphens }
     *     
     */
    public ExtendedOrganizationInfoWithHyphens getFactorInfo() {
        return factorInfo;
    }

    /**
     * Sets the value of the factorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtendedOrganizationInfoWithHyphens }
     *     
     */
    public void setFactorInfo(ExtendedOrganizationInfoWithHyphens value) {
        this.factorInfo = value;
    }

    /**
     * Gets the value of the mainAssignMonetaryClaim property.
     * 
     * @return
     *     possible object is
     *     {@link TransferBase820 }
     *     
     */
    public TransferBase820 getMainAssignMonetaryClaim() {
        return mainAssignMonetaryClaim;
    }

    /**
     * Sets the value of the mainAssignMonetaryClaim property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferBase820 }
     *     
     */
    public void setMainAssignMonetaryClaim(TransferBase820 value) {
        this.mainAssignMonetaryClaim = value;
    }

    /**
     * Gets the value of the sellerInfoCircumPublicProc property.
     * 
     * @return
     *     possible object is
     *     {@link UniversalTransferDocumentWithHyphens.SellerInfoCircumPublicProc }
     *     
     */
    public UniversalTransferDocumentWithHyphens.SellerInfoCircumPublicProc getSellerInfoCircumPublicProc() {
        return sellerInfoCircumPublicProc;
    }

    /**
     * Sets the value of the sellerInfoCircumPublicProc property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversalTransferDocumentWithHyphens.SellerInfoCircumPublicProc }
     *     
     */
    public void setSellerInfoCircumPublicProc(UniversalTransferDocumentWithHyphens.SellerInfoCircumPublicProc value) {
        this.sellerInfoCircumPublicProc = value;
    }

    /**
     * Gets the value of the documentShipments property.
     * 
     * @return
     *     possible object is
     *     {@link UniversalTransferDocumentWithHyphens.DocumentShipments }
     *     
     */
    public UniversalTransferDocumentWithHyphens.DocumentShipments getDocumentShipments() {
        return documentShipments;
    }

    /**
     * Sets the value of the documentShipments property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniversalTransferDocumentWithHyphens.DocumentShipments }
     *     
     */
    public void setDocumentShipments(UniversalTransferDocumentWithHyphens.DocumentShipments value) {
        this.documentShipments = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunction(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the approvedStructureAdditionalInfoFields property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedStructureAdditionalInfoFields() {
        return approvedStructureAdditionalInfoFields;
    }

    /**
     * Sets the value of the approvedStructureAdditionalInfoFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedStructureAdditionalInfoFields(String value) {
        this.approvedStructureAdditionalInfoFields = value;
    }

    /**
     * Gets the value of the senderFnsParticipantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderFnsParticipantId() {
        return senderFnsParticipantId;
    }

    /**
     * Sets the value of the senderFnsParticipantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderFnsParticipantId(String value) {
        this.senderFnsParticipantId = value;
    }

    /**
     * Gets the value of the recipientFnsParticipantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientFnsParticipantId() {
        return recipientFnsParticipantId;
    }

    /**
     * Sets the value of the recipientFnsParticipantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientFnsParticipantId(String value) {
        this.recipientFnsParticipantId = value;
    }

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the documentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentDate() {
        return documentDate;
    }

    /**
     * Sets the value of the documentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentDate(String value) {
        this.documentDate = value;
    }

    /**
     * Gets the value of the documentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the currencyRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrencyRate() {
        return currencyRate;
    }

    /**
     * Sets the value of the currencyRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrencyRate(BigDecimal value) {
        this.currencyRate = value;
    }

    /**
     * Gets the value of the revisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionDate() {
        return revisionDate;
    }

    /**
     * Sets the value of the revisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionDate(String value) {
        this.revisionDate = value;
    }

    /**
     * Gets the value of the hyphenRevisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHyphenRevisionDate() {
        if (hyphenRevisionDate == null) {
            return "false";
        } else {
            return hyphenRevisionDate;
        }
    }

    /**
     * Sets the value of the hyphenRevisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHyphenRevisionDate(String value) {
        this.hyphenRevisionDate = value;
    }

    /**
     * Gets the value of the revisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRevisionNumber() {
        return revisionNumber;
    }

    /**
     * Sets the value of the revisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRevisionNumber(BigInteger value) {
        this.revisionNumber = value;
    }

    /**
     * Gets the value of the hyphenRevisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHyphenRevisionNumber() {
        if (hyphenRevisionNumber == null) {
            return "false";
        } else {
            return hyphenRevisionNumber;
        }
    }

    /**
     * Sets the value of the hyphenRevisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHyphenRevisionNumber(String value) {
        this.hyphenRevisionNumber = value;
    }

    /**
     * Gets the value of the documentCreator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentCreator() {
        return documentCreator;
    }

    /**
     * Sets the value of the documentCreator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentCreator(String value) {
        this.documentCreator = value;
    }

    /**
     * Gets the value of the documentCreatorBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentCreatorBase() {
        return documentCreatorBase;
    }

    /**
     * Sets the value of the documentCreatorBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentCreatorBase(String value) {
        this.documentCreatorBase = value;
    }

    /**
     * Gets the value of the governmentContractInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovernmentContractInfo() {
        return governmentContractInfo;
    }

    /**
     * Sets the value of the governmentContractInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovernmentContractInfo(String value) {
        this.governmentContractInfo = value;
    }

    /**
     * Gets the value of the circumFormatInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCircumFormatInvoice() {
        return circumFormatInvoice;
    }

    /**
     * Sets the value of the circumFormatInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCircumFormatInvoice(String value) {
        this.circumFormatInvoice = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Buyer" type="{}ExtendedOrganizationInfoWithHyphens" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "buyer"
    })
    public static class Buyers {

        @XmlElement(name = "Buyer", required = true)
        protected List<ExtendedOrganizationInfoWithHyphens> buyer;

        /**
         * Gets the value of the buyer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the buyer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBuyer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExtendedOrganizationInfoWithHyphens }
         * 
         * 
         */
        public List<ExtendedOrganizationInfoWithHyphens> getBuyer() {
            if (buyer == null) {
                buyer = new ArrayList<ExtendedOrganizationInfoWithHyphens>();
            }
            return this.buyer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Consignee" type="{}ExtendedOrganizationInfoWithHyphens" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "consignee"
    })
    public static class Consignees {

        @XmlElement(name = "Consignee", required = true)
        protected List<ExtendedOrganizationInfoWithHyphens> consignee;

        /**
         * Gets the value of the consignee property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the consignee property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConsignee().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExtendedOrganizationInfoWithHyphens }
         * 
         * 
         */
        public List<ExtendedOrganizationInfoWithHyphens> getConsignee() {
            if (consignee == null) {
                consignee = new ArrayList<ExtendedOrganizationInfoWithHyphens>();
            }
            return this.consignee;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DocumentShipment" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Name" use="required" type="{}string255" /&gt;
     *                 &lt;attribute name="Number" use="required" type="{}string255" /&gt;
     *                 &lt;attribute name="Date" type="{}date" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentShipment"
    })
    public static class DocumentShipments {

        @XmlElement(name = "DocumentShipment", required = true)
        protected List<UniversalTransferDocumentWithHyphens.DocumentShipments.DocumentShipment> documentShipment;

        /**
         * Gets the value of the documentShipment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the documentShipment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocumentShipment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UniversalTransferDocumentWithHyphens.DocumentShipments.DocumentShipment }
         * 
         * 
         */
        public List<UniversalTransferDocumentWithHyphens.DocumentShipments.DocumentShipment> getDocumentShipment() {
            if (documentShipment == null) {
                documentShipment = new ArrayList<UniversalTransferDocumentWithHyphens.DocumentShipments.DocumentShipment>();
            }
            return this.documentShipment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Name" use="required" type="{}string255" /&gt;
         *       &lt;attribute name="Number" use="required" type="{}string255" /&gt;
         *       &lt;attribute name="Date" type="{}date" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DocumentShipment {

            @XmlAttribute(name = "Name", required = true)
            protected String name;
            @XmlAttribute(name = "Number", required = true)
            protected String number;
            @XmlAttribute(name = "Date")
            protected String date;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the number property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumber() {
                return number;
            }

            /**
             * Sets the value of the number property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumber(String value) {
                this.number = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDate(String value) {
                this.date = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Document" type="{}PaymentDocumentInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "document"
    })
    public static class PaymentDocuments {

        @XmlElement(name = "Document")
        protected List<PaymentDocumentInfo> document;

        /**
         * Gets the value of the document property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the document property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PaymentDocumentInfo }
         * 
         * 
         */
        public List<PaymentDocumentInfo> getDocument() {
            if (document == null) {
                document = new ArrayList<PaymentDocumentInfo>();
            }
            return this.document;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="DateStateContract" use="required" type="{}date" /&gt;
     *       &lt;attribute name="NumberStateContract" use="required" type="{}string100" /&gt;
     *       &lt;attribute name="PersonalAccountSeller"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;length value="11"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="SellerBudjetClassCode" type="{}string20f" /&gt;
     *       &lt;attribute name="SellerTargetCode" type="{}string20f" /&gt;
     *       &lt;attribute name="SellerTreasuryCode"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;minLength value="1"/&gt;
     *             &lt;maxLength value="4"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="SellerTreasuryName" type="{}string2000" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SellerInfoCircumPublicProc {

        @XmlAttribute(name = "DateStateContract", required = true)
        protected String dateStateContract;
        @XmlAttribute(name = "NumberStateContract", required = true)
        protected String numberStateContract;
        @XmlAttribute(name = "PersonalAccountSeller")
        protected String personalAccountSeller;
        @XmlAttribute(name = "SellerBudjetClassCode")
        protected String sellerBudjetClassCode;
        @XmlAttribute(name = "SellerTargetCode")
        protected String sellerTargetCode;
        @XmlAttribute(name = "SellerTreasuryCode")
        protected String sellerTreasuryCode;
        @XmlAttribute(name = "SellerTreasuryName")
        protected String sellerTreasuryName;

        /**
         * Gets the value of the dateStateContract property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateStateContract() {
            return dateStateContract;
        }

        /**
         * Sets the value of the dateStateContract property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateStateContract(String value) {
            this.dateStateContract = value;
        }

        /**
         * Gets the value of the numberStateContract property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumberStateContract() {
            return numberStateContract;
        }

        /**
         * Sets the value of the numberStateContract property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumberStateContract(String value) {
            this.numberStateContract = value;
        }

        /**
         * Gets the value of the personalAccountSeller property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonalAccountSeller() {
            return personalAccountSeller;
        }

        /**
         * Sets the value of the personalAccountSeller property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonalAccountSeller(String value) {
            this.personalAccountSeller = value;
        }

        /**
         * Gets the value of the sellerBudjetClassCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSellerBudjetClassCode() {
            return sellerBudjetClassCode;
        }

        /**
         * Sets the value of the sellerBudjetClassCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSellerBudjetClassCode(String value) {
            this.sellerBudjetClassCode = value;
        }

        /**
         * Gets the value of the sellerTargetCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSellerTargetCode() {
            return sellerTargetCode;
        }

        /**
         * Sets the value of the sellerTargetCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSellerTargetCode(String value) {
            this.sellerTargetCode = value;
        }

        /**
         * Gets the value of the sellerTreasuryCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSellerTreasuryCode() {
            return sellerTreasuryCode;
        }

        /**
         * Sets the value of the sellerTreasuryCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSellerTreasuryCode(String value) {
            this.sellerTreasuryCode = value;
        }

        /**
         * Gets the value of the sellerTreasuryName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSellerTreasuryName() {
            return sellerTreasuryName;
        }

        /**
         * Sets the value of the sellerTreasuryName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSellerTreasuryName(String value) {
            this.sellerTreasuryName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Seller" type="{}ExtendedOrganizationInfoWithHyphens" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seller"
    })
    public static class Sellers {

        @XmlElement(name = "Seller", required = true)
        protected List<ExtendedOrganizationInfoWithHyphens> seller;

        /**
         * Gets the value of the seller property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the seller property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSeller().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExtendedOrganizationInfoWithHyphens }
         * 
         * 
         */
        public List<ExtendedOrganizationInfoWithHyphens> getSeller() {
            if (seller == null) {
                seller = new ArrayList<ExtendedOrganizationInfoWithHyphens>();
            }
            return this.seller;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Shipper" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice minOccurs="0"&gt;
     *                   &lt;element name="OrganizationDetails" type="{}ExtendedOrganizationDetailsWithHyphens"/&gt;
     *                   &lt;element name="OrganizationReference" type="{}ExtendedOrganizationReference"/&gt;
     *                 &lt;/choice&gt;
     *                 &lt;attribute name="SameAsSeller" default="false"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;enumeration value="true"/&gt;
     *                       &lt;enumeration value="false"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shipper"
    })
    public static class Shippers {

        @XmlElement(name = "Shipper", required = true)
        protected List<UniversalTransferDocumentWithHyphens.Shippers.Shipper> shipper;

        /**
         * Gets the value of the shipper property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the shipper property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getShipper().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UniversalTransferDocumentWithHyphens.Shippers.Shipper }
         * 
         * 
         */
        public List<UniversalTransferDocumentWithHyphens.Shippers.Shipper> getShipper() {
            if (shipper == null) {
                shipper = new ArrayList<UniversalTransferDocumentWithHyphens.Shippers.Shipper>();
            }
            return this.shipper;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice minOccurs="0"&gt;
         *         &lt;element name="OrganizationDetails" type="{}ExtendedOrganizationDetailsWithHyphens"/&gt;
         *         &lt;element name="OrganizationReference" type="{}ExtendedOrganizationReference"/&gt;
         *       &lt;/choice&gt;
         *       &lt;attribute name="SameAsSeller" default="false"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;enumeration value="true"/&gt;
         *             &lt;enumeration value="false"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "organizationDetails",
            "organizationReference"
        })
        public static class Shipper {

            @XmlElement(name = "OrganizationDetails")
            protected ExtendedOrganizationDetailsWithHyphens organizationDetails;
            @XmlElement(name = "OrganizationReference")
            protected ExtendedOrganizationReference organizationReference;
            @XmlAttribute(name = "SameAsSeller")
            protected String sameAsSeller;

            /**
             * Gets the value of the organizationDetails property.
             * 
             * @return
             *     possible object is
             *     {@link ExtendedOrganizationDetailsWithHyphens }
             *     
             */
            public ExtendedOrganizationDetailsWithHyphens getOrganizationDetails() {
                return organizationDetails;
            }

            /**
             * Sets the value of the organizationDetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link ExtendedOrganizationDetailsWithHyphens }
             *     
             */
            public void setOrganizationDetails(ExtendedOrganizationDetailsWithHyphens value) {
                this.organizationDetails = value;
            }

            /**
             * Gets the value of the organizationReference property.
             * 
             * @return
             *     possible object is
             *     {@link ExtendedOrganizationReference }
             *     
             */
            public ExtendedOrganizationReference getOrganizationReference() {
                return organizationReference;
            }

            /**
             * Sets the value of the organizationReference property.
             * 
             * @param value
             *     allowed object is
             *     {@link ExtendedOrganizationReference }
             *     
             */
            public void setOrganizationReference(ExtendedOrganizationReference value) {
                this.organizationReference = value;
            }

            /**
             * Gets the value of the sameAsSeller property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSameAsSeller() {
                if (sameAsSeller == null) {
                    return "false";
                } else {
                    return sameAsSeller;
                }
            }

            /**
             * Sets the value of the sameAsSeller property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSameAsSeller(String value) {
                this.sameAsSeller = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice maxOccurs="unbounded"&gt;
     *         &lt;element name="SignerReference" type="{}SignerReference"/&gt;
     *         &lt;element name="SignerDetails" type="{}ExtendedSignerDetails_SellerTitle"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "signerReferenceOrSignerDetails"
    })
    public static class Signers {

        @XmlElements({
            @XmlElement(name = "SignerReference", type = SignerReference.class),
            @XmlElement(name = "SignerDetails", type = ExtendedSignerDetailsSellerTitle.class)
        })
        protected List<Object> signerReferenceOrSignerDetails;

        /**
         * Gets the value of the signerReferenceOrSignerDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the signerReferenceOrSignerDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSignerReferenceOrSignerDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SignerReference }
         * {@link ExtendedSignerDetailsSellerTitle }
         * 
         * 
         */
        public List<Object> getSignerReferenceOrSignerDetails() {
            if (signerReferenceOrSignerDetails == null) {
                signerReferenceOrSignerDetails = new ArrayList<Object>();
            }
            return this.signerReferenceOrSignerDetails;
        }

    }

}
