//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.29 at 01:59:19 PM MSK 
//


package ru.grinn.diadocsoap.xjs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Waybills complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Waybills"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Waybill" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="TransferDocumentNumber" use="required" type="{}string255" /&gt;
 *                 &lt;attribute name="TransferDocumentDate" use="required" type="{}date" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Waybills", propOrder = {
    "waybill"
})
public class Waybills {

    @XmlElement(name = "Waybill", required = true)
    protected List<Waybills.Waybill> waybill;

    /**
     * Gets the value of the waybill property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waybill property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaybill().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Waybills.Waybill }
     * 
     * 
     */
    public List<Waybills.Waybill> getWaybill() {
        if (waybill == null) {
            waybill = new ArrayList<Waybills.Waybill>();
        }
        return this.waybill;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="TransferDocumentNumber" use="required" type="{}string255" /&gt;
     *       &lt;attribute name="TransferDocumentDate" use="required" type="{}date" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Waybill {

        @XmlAttribute(name = "TransferDocumentNumber", required = true)
        protected String transferDocumentNumber;
        @XmlAttribute(name = "TransferDocumentDate", required = true)
        protected String transferDocumentDate;

        /**
         * Gets the value of the transferDocumentNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransferDocumentNumber() {
            return transferDocumentNumber;
        }

        /**
         * Sets the value of the transferDocumentNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransferDocumentNumber(String value) {
            this.transferDocumentNumber = value;
        }

        /**
         * Gets the value of the transferDocumentDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransferDocumentDate() {
            return transferDocumentDate;
        }

        /**
         * Sets the value of the transferDocumentDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransferDocumentDate(String value) {
            this.transferDocumentDate = value;
        }

    }

}
